### ISSUE TITLE
support for different dotenv files?

### ISSUE THREAD

**Issue by moritzraho** [adobe/aio-lib-core-config#19]
as of now only supports `.env`, might be good to also be able to pass different file names?

**Comment by shazron** [comment]
It's possible if we pass in the whole path to the file to the `config` method: https://github.com/motdotla/dotenv/blob/e8744104cd3c8b87d258dc153f72b5216ecb4fac/lib/main.js#L78-L85

**Comment by meryllblanchet** [comment]
Closing for now as we are aiming to optimize apps configuration.
