### ISSUE TITLE
AIO get Configuration returns an empty list

### ISSUE THREAD

**Issue by OmarEltobgy** [adobe/aio-lib-core-config#33]
This line is only calling config.get and not return anything
The result is that the configuration aren't lodaed properly and this affects AIO APP Plugin that we are using for deploying runtime actions.

Can you please solve this problem and issue a new release of aio-cli as we need this change asap ?  
https://github.com/adobe/aio-lib-core-config/blob/0764cad985c8d12b6e6114981fba11cab43f88c3/src/index.js#L30

**Comment by shazron** [comment]
Not sure how this got pass the tests. I'll add a failing test and fix asap

**Comment by OmarEltobgy** [comment]
Thanks a lot! 
It is a very weird bug. May be the tests don't go throught the index api ? 
I have been debugging the aio-cli code for a day to finally know this bug. It was an interesting process 😄
